### ISSUE TITLE
Add missing symbol

### ISSUE THREAD

**Issue by gregthompson27** [Ethan-Mounsey/Ethan-Mounsey.github.io#1]
https://github.com/Ethan-Mounsey/Ethan-Mounsey.github.io/blob/37f71af248767be4f728bc4c5317a15f4981acdc/index.html#L26

@Ethan-Mounsey, make sure to close your `img` tag with a `>` symbol at the end of line 26!

**Comment by JoshHunter11** [comment]
@gregthompson27 issue resolved
